# Generated by Django 6.0.3 on 2026-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0013_stoppoint_description_stoppoint_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stoppoint',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stopusage',
            name='line_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
