# Generated by Django 6.0.3 on 2026-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0014_alter_datasource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopusage',
            name='line_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
