# Generated by Django 6.0.3 on 2026-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='license',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
