# Generated by Django 6.0.3 on 2026-03-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_vehiclecode_unique_vehicle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallivery',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL to use as the livery icon', verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='livery',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL to use as the livery icon', verbose_name='Image URL'),
        ),
    ]
